version: '3.9'
services:
  lofhen-db:
    container_name: lofhen-db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
